application: my-app
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- remote_api: on

inbound_services:
- warmup

error_handlers:
- file: templates/error_handlers/default_error.html

- error_code: over_quota
  file: templates/error_handlers/over_quota.html

- error_code: dos_api_denial
  file: templates/error_handlers/dos_api_denial.html

- error_code: timeout
  file: templates/error_handlers/timeout.html

handlers:
#- url: /favicon\.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico
#  mime_type: image/vnd.microsoft.icon

#- url: /robots\.txt
#  static_files: static/robots.txt
#  upload: static/robots.txt

#- url: /static
#  static_dir: static

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /.*
  script: main.py
