#!/usr/bin/env python
# EASY-INSTALL-ENTRY-SCRIPT: 'Babel==0.9.4','console_scripts','pybabel'
__requires__ = 'Babel==0.9.4'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('Babel==0.9.4', 'console_scripts', 'pybabel')()
)
